# -*- coding: utf-8 -*-
# The topbar's "Points Spent" headline number blends real + estimated costs
# (colored blue, ~199 instead of 167) when the build includes at least one
# purchased-but-unconfirmed rank with a guess - the ~ prefix and color are
# the only visible cue; the confirmed/estimated breakdown lives in the
# title tooltip only, same hover-to-disclose pattern as every other
# estimate badge in the app (no separate visible note element anymore -
# topbar is glanceable-density territory). Critically, nothing else in the
# app - Progression's own running total, chief among them - is ever
# computed from the blended figure; that's the number that used to matter
# for affordability before the total-points/remaining concept was removed,
# and still matters for Progression's owned/to-go split and per-step
# running totals. This is a real shared build with several purchased-but-
# unconfirmed ranks (Combat Stability, First Aid, Innate Eminence, Improved
# Mend), independently verified by hand: real total 167, guesses add 32,
# so the headline should read "~199".
#
# The BUILD code below also happens to be a genuine backward-compatibility
# case: it was generated by an older version of the app, before the
# total-points concept was removed, and still carries a "t" (totalPoints)
# field in its decoded payload - loading it here without error, with
# nothing depending on that field anymore, is itself the regression test
# for "an old share link/save must not break just because a field it used
# to carry stopped being read."
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from playwright.sync_api import sync_playwright

BASE = "http://localhost:8743/index.html"
BUILD = "H4sIAAAAAAAACm2QwWrEMAxE_2XOc7DslZz4D3roFxgfQhuWQLotS2gPpf9eZAe2h-InxrY0c9A3PlEi8YJSZ2ZqI3YUDcSBIiEE4o5SqzE11sxLY536XWSIuqlG6a1oFJfMqbEm6S-NvaeJ5qLjc0xaGCkhd52VqTXiA8Vtg2jU9MCCk4Qx_4-HqfrQ6YlUY5QH-TwTJ1ovo8jJrCee00v_0ogv38glEE-37diWHcSxLjt8N4F43l6vy9sK4v2-3K4rWvv5BaiyIJppAQAA"

with sync_playwright() as p:
    browser = p.chromium.launch(channel="chrome", headless=True)
    page = browser.new_page(viewport={"width": 1400, "height": 900})
    errors = []
    page.on("pageerror", lambda exc: errors.append(str(exc)))
    page.on("dialog", lambda d: d.accept())

    # --- Fresh page, nothing purchased: plain real number, red, no note. ---
    page.goto(BASE)
    page.wait_for_selector("#treeWrap .node")
    sv0 = page.locator("#spentValue")
    print("fresh spentValue text/class:", sv0.inner_text(), sv0.get_attribute("class"))
    assert sv0.inner_text() == "0"
    assert sv0.get_attribute("class") is None
    color0 = sv0.evaluate("el => getComputedStyle(el).color")
    assert color0 == "rgb(217, 76, 76)", f"FAIL: expected real 'spent' red, got {color0}"
    assert sv0.get_attribute("title") is None
    print("PASS: no guesses purchased -> plain real number, red, no tooltip")

    # --- Load a build with several purchased-but-unconfirmed ranks. This
    # build code was generated by an older app version and still embeds a
    # "t" (totalPoints) field the app no longer reads at all - loading it
    # without error IS the backward-compatibility check. ---
    errors_before_load = len(errors)
    page.goto(f"{BASE}?build={BUILD}")
    page.wait_for_selector("#treeWrap .node")
    page.wait_for_timeout(200)
    assert len(errors) == errors_before_load, f"FAIL: loading an old build with a stale 't' field threw: {errors}"
    print("PASS: an old build code carrying a stripped-out 't' (totalPoints) field loads without error")

    sv = page.locator("#spentValue")
    print("spentValue text:", sv.inner_text())
    assert sv.inner_text() == "~199"
    assert "is-estimate" in sv.get_attribute("class")
    color = sv.evaluate("el => getComputedStyle(el).color")
    print("spentValue computed color:", color)
    assert color == "rgb(90, 169, 230)", f"FAIL: blended headline should render blue, got {color}"

    title = sv.get_attribute("title")
    print("spentValue title:", title)
    assert title == "167 confirmed + 32 estimated.", f"FAIL: unexpected tooltip text: {title}"
    print("PASS: headline blends to ~199 in blue, full breakdown lives only in the tooltip")

    # --- Progression's own running total (built straight from costNum(),
    # never a guess) must stay the real 167, proving the blend is purely a
    # topbar display choice and never leaks into the rest of the app. ---
    page.click('button[data-tab="progression"]')
    page.wait_for_timeout(100)
    real_total = page.locator(".progression-row .cost-total").last.inner_text()
    print("Progression's real running total (must stay 167, not the blended 199):", real_total)
    assert real_total == "167 total", f"FAIL: expected Progression's real total to stay 167, got {real_total}"
    print("PASS: Progression's running total stays real even while the topbar headline blends in estimates")

    print("ERRORS:", errors)
    assert not errors
    browser.close()
    print("ALL PASS")
