// Pattern-inferred estimates for the numeric values inside AA effect
// descriptions the wiki hasn't documented yet, generated by
// wiki-sync/guess_effects.py - see that script's docstring for the
// actual methodology. DO NOT hand-edit; rerun the generator instead,
// which recomputes this file from scratch every time rather than
// merging - a guess that no longer has corroborating evidence (or
// whose slot got confirmed in data.src.js) simply won't reappear.
//
// Keyed exactly like aaIds.js's AA_ID_TABLE (scope:className:key), then
// by progression index (order the progression appears in the
// description, as a string) and rank index (also as a string,
// matching that progression's slot position) to a guess. Only ever
// consulted by the app when the real slot text is exactly "?" - a
// guess never substitutes for a real value anywhere descriptions are
// otherwise read (search, export text) - purely a display hint.
export const EFFECT_GUESS_TABLE = {
  "archetype::burst-of-power": { "0": { "2": { value: 15, confidence: "very-low", basedOn: [], manual: true } } },
  "archetype::spell-casting-subtlety": { "0": { "1": { value: 10, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 15, confidence: "very-low", basedOn: [], manual: true }, "3": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "4": { value: 25, confidence: "very-low", basedOn: [], manual: true }, "5": { value: 30, confidence: "very-low", basedOn: [], manual: true } } },
  "class:Bard:jam-fest": { "0": { "1": { value: 3, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 5, confidence: "very-low", basedOn: [], manual: true } } },
  "class:Druid:quick-evacuation": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 30, confidence: "very-low", basedOn: [], manual: true } } },
  "class:Wizard:quick-evacuation": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 30, confidence: "very-low", basedOn: [], manual: true } } },
  "general::adamant-will": { "0": { "2": { value: 60, confidence: "very-low", basedOn: [], manual: true }, "3": { value: 80, confidence: "very-low", basedOn: [], manual: true } }, "1": { "2": { value: 45, confidence: "very-low", basedOn: [], manual: true }, "3": { value: 60, confidence: "very-low", basedOn: [], manual: true } } },
  "general::alchemy-mastery": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 40, confidence: "very-low", basedOn: [], manual: true } } },
  "general::baking-mastery": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 40, confidence: "very-low", basedOn: [], manual: true } } },
  "general::blacksmithing-mastery": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 40, confidence: "very-low", basedOn: [], manual: true } } },
  "general::brewing-mastery": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 40, confidence: "very-low", basedOn: [], manual: true } } },
  "general::combat-fury": { "0": { "1": { value: 3, confidence: "low", basedOn: [], interpolated: true } } },
  "general::combat-stability": { "0": { "2": { value: 10, confidence: "very-low", basedOn: [], manual: true } } },
  "general::fletching-mastery": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 40, confidence: "very-low", basedOn: [], manual: true } } },
  "general::innate-eminence": { "0": { "3": { value: 8, confidence: "very-low", basedOn: [], manual: true }, "4": { value: 10, confidence: "very-low", basedOn: [], manual: true } } },
  "general::innate-lung-capacity": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 30, confidence: "very-low", basedOn: [], manual: true } } },
  "general::innate-metabolism": { "0": { "2": { value: 140, confidence: "very-low", basedOn: [], manual: true } } },
  "general::innate-regeneration": { "0": { "5": { value: 6, confidence: "very-low", basedOn: [], manual: true }, "6": { value: 7, confidence: "very-low", basedOn: [], manual: true } } },
  "general::innate-spell-resistance": { "0": { "1": { value: 4, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 6, confidence: "very-low", basedOn: [], manual: true }, "3": { value: 8, confidence: "very-low", basedOn: [], manual: true }, "4": { value: 10, confidence: "very-low", basedOn: [], manual: true } } },
  "general::jewel-craft-mastery": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 40, confidence: "very-low", basedOn: [], manual: true } } },
  "general::packrat": { "0": { "3": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "4": { value: 25, confidence: "very-low", basedOn: [], manual: true }, "5": { value: 30, confidence: "very-low", basedOn: [], manual: true }, "6": { value: 35, confidence: "very-low", basedOn: [], manual: true }, "7": { value: 40, confidence: "very-low", basedOn: [], manual: true }, "8": { value: 45, confidence: "very-low", basedOn: [], manual: true }, "9": { value: 50, confidence: "very-low", basedOn: [], manual: true } } },
  "general::pottery-mastery": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 40, confidence: "very-low", basedOn: [], manual: true } } },
  "general::tailoring-mastery": { "0": { "1": { value: 20, confidence: "very-low", basedOn: [], manual: true }, "2": { value: 40, confidence: "very-low", basedOn: [], manual: true } } },
  "special::banestrike": { "0": { "2": { value: 6, confidence: "very-low", basedOn: [], manual: true }, "3": { value: 8, confidence: "very-low", basedOn: [], manual: true } } }
};
