#!/usr/bin/env python3
"""
Maintains src/aaIds.js — the append-only numeric id table used by the
compact share/export wire format (see exportImport.js's BUILD_CODE v2 and
keys.js's idForKey/entryForId). Run by hand whenever data.src.js changes:

    python wiki-sync/assign_aa_ids.py

For every AA currently in data.src.js, computes the same (scope, className,
key) identity keys.js itself computes (slugified name, with the same
auto-vs-non-auto disambiguation for a repeated name within one category).
Anything already in src/aaIds.js keeps its existing number, unconditionally.
Anything new gets the next unused integer, appended at the end. An id is
NEVER reassigned and NEVER reused, even for an AA that's since been removed
from data.src.js — entries for since-removed AAs are left in the table
rather than deleted, so an old share link's id still means what it always
meant (resolves to "gone", same as an unknown name key does, rather than
risking a future different AA silently inheriting its number).

This mirrors exactly how LEGACY_AA_ORDER in keys.js must never be edited
after the fact - the numbers are a historical record, not a live view.
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA_SRC = HERE.parent / "data.src.js"
IDS_FILE = HERE.parent / "src" / "aaIds.js"

DATA_CATEGORY_START = re.compile(r'^(general|archetype|special):\s*\[')
DATA_CLASS_START = re.compile(r'^"([^"]+)":\s*\[')
DATA_ENTRY_NAME = re.compile(r'name:\s*"((?:[^"\\]|\\.)*)"')
DATA_ENTRY_AUTO = re.compile(r'\bauto:\s*true')


def slugify(name):
    s = name.lower().replace("'", "")
    s = re.sub(r'[^a-z0-9]+', '-', s).strip('-')
    return s


def parse_data_src():
    """Returns list of (scope, className, name, auto) in AA_DATA order."""
    text = DATA_SRC.read_text(encoding="utf-8")
    current_cat = None
    out = []
    for line in text.split("\n"):
        s = line.strip()
        m = DATA_CATEGORY_START.match(s)
        if m:
            current_cat = (m.group(1), None)
            continue
        m = DATA_CLASS_START.match(s)
        if m:
            current_cat = ("class", m.group(1))
            continue
        if s.startswith("classes:") or not s.startswith("{ name:"):
            continue
        nm = DATA_ENTRY_NAME.search(s)
        if not nm or not current_cat:
            continue
        auto = bool(DATA_ENTRY_AUTO.search(s))
        scope, className = current_cat
        out.append((scope, className, nm.group(1), auto))
    return out


def compute_keys(entries):
    """
    entries: list of (scope, className, name, auto) in AA_DATA order.
    Returns list of (scope, className, key) with the same auto-vs-non-auto
    disambiguation keys.js's keyForEntryIdx applies for a repeated name
    within one (scope, className) bucket.
    """
    buckets = {}
    for i, (scope, className, name, auto) in enumerate(entries):
        buckets.setdefault((scope, className), []).append(i)

    result = [None] * len(entries)
    for (scope, className), idxs in buckets.items():
        names = [entries[i][2] for i in idxs]
        autos = [entries[i][3] for i in idxs]
        slugs = [slugify(n) for n in names]
        for pos, i in enumerate(idxs):
            base = slugs[pos]
            same = [j for j in range(len(idxs)) if slugs[j] == base]
            if len(same) <= 1:
                key = base
            elif not autos[pos]:
                key = base
            else:
                auto_siblings = [j for j in same if autos[j]]
                auto_pos = auto_siblings.index(pos)
                key = f"{base}-auto" if auto_pos == 0 else f"{base}-auto-{auto_pos + 1}"
            result[i] = (scope, className, key)
    return result


def id_key(scope, className, key):
    return f"{scope}:{className or ''}:{key}"


def load_existing_table():
    if not IDS_FILE.exists():
        return {}
    text = IDS_FILE.read_text(encoding="utf-8")
    m = re.search(r'AA_ID_TABLE\s*=\s*(\{.*?\n\});', text, re.DOTALL)
    if not m:
        raise RuntimeError(f"Could not find AA_ID_TABLE object in {IDS_FILE}")
    # The table is written as valid JSON-ish JS (double-quoted keys, plain
    # integers) - safe to parse as JSON directly.
    obj_text = m.group(1)
    return json.loads(obj_text)


def write_table(table):
    # Sorted by id for a readable diff/history, not that it affects meaning.
    ordered = sorted(table.items(), key=lambda kv: kv[1])
    lines = [f'  "{k}": {v}' for k, v in ordered]
    body = ",\n".join(lines)
    content = (
        "// Append-only numeric id table for every AA, generated by\n"
        "// wiki-sync/assign_aa_ids.py. DO NOT hand-edit the numbers, and\n"
        "// never remove or renumber an existing entry, even for an AA no\n"
        "// longer in data.src.js - see that script's docstring for why.\n"
        "// Consumed by keys.js (idForKey/entryForId), used only by the\n"
        "// compact share/export wire format.\n"
        "export const AA_ID_TABLE = {\n"
        f"{body}\n"
        "};\n"
    )
    # Plain open()+write() rather than Path.write_text(), since write_text's
    # newline= parameter needs Python 3.10+. newline="\n" keeps the
    # working-tree file LF on Windows too - .gitattributes (* text=auto
    # eol=lf) would normalize it on commit either way, but writing it
    # correctly to begin with means git status doesn't show a phantom diff
    # the moment git touches the file.
    with open(IDS_FILE, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def main():
    entries = parse_data_src()
    keyed = compute_keys(entries)

    existing = load_existing_table()
    next_id = (max(existing.values()) + 1) if existing else 0

    added = []
    for scope, className, key in keyed:
        ik = id_key(scope, className, key)
        if ik not in existing:
            existing[ik] = next_id
            added.append((ik, next_id))
            next_id += 1

    write_table(existing)

    print(f"Parsed {len(entries)} AA entries from data.src.js")
    print(f"Total ids in table: {len(existing)}")
    if added:
        print(f"Newly assigned ({len(added)}):")
        for ik, i in added:
            print(f"  {i}: {ik}")
    else:
        print("No new AAs since last run - table unchanged.")


if __name__ == "__main__":
    sys.exit(main())
